### ISSUE TITLE
Acqisition has stopped working

### ISSUE THREAD

**Issue by TaiHiko** [xyzz/acquisition#276] opened 2016-03-21 18:33 UTC
The problem is that Acquisition can't start on Perandus league. After loging all i get is this: 
![image](https://cloud.githubusercontent.com/assets/17990205/13929517/d028cd04-ef9a-11e5-8e0d-df699cd01dea.png)
Weird thing is that on other leagues everything works properly(HC Perandus, Standard and HC).
I tryed to reinstal Acquisition to version .5c, .5d and .5b and on all of them have the same problem.

**Comment by ericsium** [comment] 2016-03-21 21:38
See #272, #275 there was a database corruption issue with .5d so it was pulled shortly after release.  If you used it it probably corrupted the perandus database which is then causing an error when loading.

To fix you need a 'fresh' database for Perandus.

Acquisition preferences are stored in %localappdata%\acquisition

you can start a 'cmd' shell and run 'cd %localappdata%\acquisition' to get there.

If you don't care about your current pricing in all leagues you can simply move or delete the 'acquisition' prefs folder which will reset everything.  If you want to still use your old league pricing and just recover perandus league it's a bit trickier.  In the 'data' folder the database are held per leauge.  The problem is that there is no great way to identify which file is associated with which league.  Back up all the files and then delete them one by one to find out which is perandus and then restore the others.

If this works for you please report back so we can close this issue.

**Comment by TaiHiko** [comment] 2016-03-21 21:51
It did helped :) Thanks for fast answer.

**Comment by Gloorf** [comment] 2016-03-23 16:03
Fixed in 98dd1051.

**Closed by Gloorf** 2016-03-23 16:03 UTC
