### ISSUE TITLE
copy shop data to clipboard and auto update are both empty

### ISSUE THREAD

**Issue by mslavery** [xyzz/acquisition#272] opened 2016-03-19 22:42 UTC

**Comment by Gloorf** [comment] 2016-03-19 22:45
Can you provide more informations ?

**Comment by Gloorf** [comment] 2016-03-19 23:04
I can reproduce this, there is really strange things happening with buyouts since aaac91d : 
at first start, everything is OK. At second start (maybe it's on fetch and not start, but wanted to test immediately), my no price tab is turned into a ~b/o 0 chaos tab. If i don't touch it, at next start the tab buyout is removed, BUT I keep the individual buyout inside the tab. If i change the buyout back to "no price", at next start i lose the individual buyouts on next start :/

**Comment by mslavery** [comment] 2016-03-19 23:06
Yeah sorry i stepped away. It happened when i set my tab to buyout 1 chaos, and from that point it wont give me any data anymore, even after changing everything to individual priced

**Comment by Gloorf** [comment] 2016-03-19 23:13
You are using 0.5d right ? If so, I suggest making a save of all your individual price (take a screenshot for example), and go back to 0.5c

**Comment by mslavery** [comment] 2016-03-19 23:16
Yeah, Ill give that a shot now, thanks. ill report back soon

**Comment by mslavery** [comment] 2016-03-19 23:25
Still no luck with relisting everything and going back to 0.5c

**Comment by ericsium** [comment] 2016-03-19 23:26
I'll look into this, can we pull this release at least temporarily?

**Comment by ericsium** [comment] 2016-03-20 01:00
@mslavery I'm having a very hard time reproducing any issues.  Started with fresh .5c install, set buyouts then moved to .5d loaded things up and didn't see any issues.  Any more info you can provide that might be helpful?

**Comment by Gloorf** [comment] 2016-03-20 01:13
@mslavery what OS are you using ?

**Comment by mslavery** [comment] 2016-03-20 01:18
I am using windows 10, 64 bit. Not sure what else i could provide to help more!

**Comment by ericsium** [comment] 2016-03-20 02:21
@mslavery thanks much for reporting this so quickly, seems like we've gotten to the bottom of this problem.

**Comment by Gloorf** [comment] 2016-03-23 16:02
Fixed in 98dd1051.

**Closed by Gloorf** 2016-03-23 16:02 UTC
Labels: bug
