### ISSUE TITLE
Losing buyout after movin item to another tab

### ISSUE THREAD

**Issue by besrezen** [xyzz/acquisition#193] opened 2015-12-20 22:54 UTC
Well, it's like said in subj - losing buyout after moving item to a different tab. If you move item on other place in same tab - buyout is present. Using latest version of programm.

**Comment by xyzz** [comment] 2015-12-20 22:55
That's not a bug, all buyouts are locked to the tab.

**Comment by besrezen** [comment] 2015-12-20 22:59
thanks for the answear, but in previous version it worked in other way. I marked items in one tab and then moved them to another, and buyouts were saved.

**Comment by izenja** [comment] 2015-12-21 08:33
It's a problem for me too, and it wasn't before. I have a staging tab where I dump items that I want to price. Once it's full enough, I price them all in acquisition then move them to the appropriate tab (helm, chest, etc). I could probably work around it but it would be nice if it worked the way it used to.

**Comment by xyzz** [comment] 2015-12-22 11:54
Having buyouts not locked to the tab an item is in led to all items (that are the same) from all tabs being priced when you price a single item, so it was changed.

The only good solution to this would be use a truly unique item identifier, but this can only be fixed by GGG and they don't seem to be very interested in this.

**Comment by besrezen** [comment] 2015-12-22 12:42
oh, i see. that's a shame ofc, but i presume you will note be unlocking byouts to all tabs.

**Closed** 2015-12-26 20:59 UTC
