### ISSUE TITLE
Identical (but different) item posted for same buyout

### ISSUE THREAD

**Issue by Vexra** [xyzz/acquisition#127] opened 2015-08-11 13:52 UTC
Happened twice now. Sold a Tabula Rasa in my shop and after selling it the Tabula from my other character got automatically added for the same buyout.

**Comment by Gloorf** [comment] 2015-08-11 14:15
Multiple of issue about it, the problem is on GGG side : they give the same hash to identical items, for example gems, maps, white item ... Can't do anything about it sadly

**Comment by xyzz** [comment] 2015-08-13 21:27
This will be fixed by #72, #75.

**Closed by xyzz** 2015-08-13 21:27 UTC
