### ISSUE TITLE
"No Price" on whole tab doesn't apply to all items

### ISSUE THREAD

**Issue by foreAndaway** [xyzz/acquisition#99] opened 2015-07-19 18:46 UTC
I have to manually select No price for each item, else everything in the tab is ignored

**Comment by xyzz** [comment] 2015-07-19 18:49
Items' buyouts override tab buyout they are in, this is by design.

**Comment by xyzz** [comment] 2015-08-08 20:30
I've tried multiple times and it seems to work fine, do you have more information on how to reproduce this?

**Comment by ericsium** [comment] 2016-05-01 14:45
The mechanism was changed a lot with #267 so closing this.

**Closed by ericsium** 2016-05-01 14:45 UTC
