### ISSUE TITLE
After 2.02 Path of Exile Update getting item errors in Main Display

### ISSUE THREAD

**Issue by KCIV** [xyzz/acquisition#138] opened 2015-08-20 03:57 UTC
http://puu.sh/jHK9R/5c7d68d47b.png

here is link to the display.

Not sure if this is an issue or just "patching" things with the new update! Keep up the great work!

![](http://puu.sh/jHK9R/5c7d68d47b.png)

**Comment by MakiabelMFE** [comment] 2015-08-20 04:52
Yep same issue here, for now I just re-priced everything again since the prices got deleted and it works fine for now.

**Comment by Tvangeste** [comment] 2015-08-20 12:26
Confirmed for me as well. Looks like GGG changed the format a bit?

all the custom set prices are gone for me :( Only per-tab prices remain intact.

We urgently need an update! :)

**Comment by xyzz** [comment] 2015-08-20 13:46
Fixed by 42fac6ab633586d089c8f1d51e85f6f15d51105f

**Closed by xyzz** 2015-08-20 13:46 UTC
Labels: bug
