### ISSUE TITLE
Shop errors with 0.2 release

### ISSUE THREAD

**Issue by bharden** [xyzz/acquisition#68] opened 2015-02-01 15:24 UTC
Since I upgraded to the 0.2 release, I'm getting a lot more errors with Acquisition.  Quite often, when I start playing and open POE and Acquisition, it overwrites my shop forum post with just "Empty" and no items listed.  Once I notice it has done this then I can usually get it fixed by doing a couple manual refreshes and force updates.  But the next time I start the clients up it usually happens again.  Sometimes I get a lot of these in the Event Log:

 WARN 2015-02-01T10:20:18.425 Submitting shop right now, the request to update shop data will be ignored 
 WARN 2015-02-01T10:20:22.203 Already submitting your shop. 
ERROR 2015-02-01T10:20:26.194 Error while submitting shop to forums: Failed to find item. Did you specify the correct location and x y? 

Never had any of these issues with 0.1, so I think possibly a bug was introduced since then.  If I'm able to narrow the problem down further, I'll post more.  Or let me know if there's any other info you need.

**Comment by xyzz** [comment] 2015-02-01 16:11
All these warnings are normal, you shouldn't try to submit shop to forums multiple times (while the previous request is still not completed). The error is most likely because of item data being out of sync, that's fairly normal too and is usually fixed with the next refresh. The only strange thing here is shop thread being overwritten with "Empty", can you give more details?

**Comment by bharden** [comment] 2015-02-01 17:01
Ok, I'm able to reproduce it by leaving POE running, close Acquisition and restart Acquisition.  It immediately updates my shop thread to "Empty".  The only things in the event log are:

Errors and warnings will be printed here
 WARN 2015-02-01T11:58:52.674 Submitting shop right now, the request to update shop data will be ignored 
 WARN 2015-02-01T11:58:54.803 Already submitting your shop. 
 WARN 2015-02-01T11:58:54.803 Submitting shop right now, the request to update shop data will be ignored 


I did not do any manual refresh/update yet.  I have auto-refresh and auto-update selected.

Now when I do a manual refresh and manual update, it updates my shop thread with the correct data again (after about 10 seconds).

**Comment by bharden** [comment] 2015-02-01 17:03
My shop thread is this one:
http://www.pathofexile.com/forum/view-thread/1121088

**Comment by xyzz** [comment] 2015-02-01 21:53
ok can you test this version: https://xyz.is/acquisition/bin/acquisition_setup_0.2-issue-68.exe I just reverted multiple shops feature because it's the one that seems to cause the issue and I'm unable to reproduce it myself

**Comment by bharden** [comment] 2015-02-01 22:31
Yeah, looks like that fixes it for me.  Just installed it, started it up, and it updated the shop correctly with no "Empty" and no error messages in the log.  Thanks!  I'll post here again if I run into any problems with it.

**Comment by xyzz** [comment] 2015-02-02 01:17
I pushed the new update, 0.2a, that disables the multishop feature, so this is closed for now. I'll work on a proper fix later.

**Closed by xyzz** 2015-02-02 01:17 UTC
Labels: bug
