### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by alfanjorfresco** [xyzz/acquisition#512] opened 2018-12-11 08:31 UTC
cannot loggin

**Comment by OssiPap** [comment] 2018-12-11 10:47
Doesn't seem to be purely an Acquisition sided problem, Procurement doesn't get through the log in either.

**Comment by alfanjorfresco** [comment] 2018-12-11 11:08
Network error: Error transferring https://pathofexile.com/login - server replieds: Service Temporarily Unavaible

**Comment by jofabian** [comment] 2018-12-11 13:06
I'm pretty sure this problem is because they implemented "DDoS protection by Cloudflare".
I get this message when I go to the login page:
"
Checking your browser before accessing pathofexile.com.
This process is automatic. Your browser will redirect to your requested content shortly.

Please allow up to 5 seconds…

DDoS protection by Cloudflare
"

**Comment by DaneelTrevize** [comment] 2018-12-11 15:33
Duplicate of #510 which has a response from xyzz.
I can also confirm [the error appears like so](https://i.imgur.com/pNDVU3U.png).

**Comment by tutanotaaa** [comment] 2018-12-11 16:57
Same error since yesterday 

Network error: Error transferring https://pathofexile.com/login - server replied: Service Temporarily Unavaible

**Comment by xyzz** [comment] 2018-12-11 19:35
As noted above, see #510

**Closed by xyzz** 2018-12-11 19:35 UTC
