### ISSUE TITLE
Acquisition is not loading [got a non-object response]

### ISSUE THREAD

**Issue by PreOwned** [xyzz/acquisition#92] opened 2015-07-12 02:54 UTC
hey, I start up acquisition and tried running with both my Steam ID and Session ID,

it pulls "27/28" and then "throttles" for 60 seconds

after 60 seconds I get an error code then again every 60 seconds or so after that these are the error codes.

any way to solve this problem?

thanks

Errors and warnings will be printed here
 WARN 2015-07-11T19:44:05.295 0 got a non-object response 
 WARN 2015-07-11T19:45:06.587 27 got a non-object response 
 WARN 2015-07-11T19:46:06.954 28 got a non-object response 
 WARN 2015-07-11T19:47:07.310 29 got a non-object response 
 WARN 2015-07-11T19:48:07.694 30 got a non-object response 
 WARN 2015-07-11T19:49:08.053 31 got a non-object response 
 WARN 2015-07-11T19:50:08.393 32 got a non-object response 
 WARN 2015-07-11T19:51:08.812 33 got a non-object response

**Comment by xyzz** [comment] 2015-07-13 13:25
Here's what I need you to do to help debug this issue:
1) Go to `%localappdata%\acquisition` and delete log.txt
2) Download and install https://xyz.is/acquisition/bin/acquisition_setup_0.2e-issue-92.exe, it's a build with a lot of logging information added
3) Run it and log into your account as usual
4) Once you reproduce the issue, send me `%localappdata%\acquisition\log.txt`, for example. paste it to https://gist.github.com/

**Comment by Tidefury** [comment] 2015-07-14 07:34
Same problem, here is the logfile:

https://gist.github.com/dc4bfd72b65f27a4759e.git

**Comment by xyzz** [comment] 2015-07-14 07:52
@wolflord2015 what's the gist url?

@Tidefury it seems it's PoE server having an error, can you go to https://www.pathofexile.com/ click on your character portrait and select TriFrost, will it display this character's items?

**Comment by Kernuppi** [comment] 2015-07-14 07:56
https://gist.github.com/anonymous/c0678851cc4c004e105b

Here's also mine logfile. problem keeps on coming

**Comment by Tidefury** [comment] 2015-07-14 07:57
No, it won't. Shows every character's items except TriFrost with which im actually logged in.

**Comment by xyzz** [comment] 2015-07-14 08:01
@Kernuppi for you it's character Nahkapenaali, can you view their items?

@Tidefury then it's indeed a problem on GGG's end. I'll try contacting them to see if it can be fixed.

**Comment by Tidefury** [comment] 2015-07-14 08:02
Good to know, thanks for your efforts!

**Comment by Kernuppi** [comment] 2015-07-14 08:04
I can see stash with no problems, but as my char items.. I can't see them

**Comment by xyzz** [comment] 2015-07-14 09:29
Chris says it's working fine, can anybody confirm the issue is gone? (i.e. you can see your character's items on the website)

**Comment by Tidefury** [comment] 2015-07-14 09:34
Still can't see TriFrost's inventory/equipment, everything else works.

**Comment by Kernuppi** [comment] 2015-07-14 10:13
I created new char, which is lvl1, it instantly shows potions I have equipped on website, but as my main char.. It doesn't show anything at website.
My friend can see those items, but for some odd reason I cannot..

**Comment by xyzz** [comment] 2015-07-14 10:14
Chris said they will look into it, thanks everybody for the log files.

**Comment by Kernuppi** [comment] 2015-07-14 10:21
Maybe the problem persist on new players and new char. Since that char is my first char and it show's nothing, but as I created second char just to see does it show anything, it actually works and shows something.
That is only reasonable thing I can get into my mind, that it just doesn't show first characters's inventory/equipped items, something with the code or.. 
I even tried Acquisition again to see if that program would work now since char's share stash, but it still gives the same non-object thingy. 
Well we just have to wait and see for an update.

Thank's a lot from your time Xyzz.
Back to grind now and check this thread every now and then.

**Comment by Tidefury** [comment] 2015-07-14 10:24
As I'm no new player and it's not my first char I guess this is not the reason...

**Comment by Kernuppi** [comment] 2015-07-14 10:25
Ahh. well that most certainly helps even more to figure out the problem

**Comment by wolflord2015** [comment] 2015-07-14 19:15
https://gist.github.com/wolflord2015/29f4c56ddd284ba0f6ee
i can see my char on the website and also the stash

**Comment by Kernuppi** [comment] 2015-07-14 20:28
I'm just here to post that my issue has been fixed on Acquisition, and on the website. I can now see my inventory/stash and able to use Acquisition.

Thank you very much Xyzz, and also thank's to chris. Thanks for taking ur time to help me, and maybe many others with similiar issues

**Comment by wolflord2015** [comment] 2015-07-14 21:41
I still get the same errors.

**Comment by Tidefury** [comment] 2015-07-16 07:46
Problem seems solved after connectivity errors yesterday.

**Comment by xyzz** [comment] 2015-07-18 11:40
Fixed by GGG, closing.

**Closed by xyzz** 2015-07-18 11:40 UTC
Labels: bug, not our bug
