### ISSUE TITLE
Pricing wiped out

### ISSUE THREAD

**Issue by sonus9** [xyzz/acquisition#275] opened 2016-03-20 20:18 UTC
It might have started with this new version of Acquisition, but I would have a tab fully and individually priced with Buyout.  After closing and opening the application, logging in by Session ID, all of the prices have been reset and I'd have to re-price everything over again.

**Comment by ericsium** [comment] 2016-03-20 23:44
Sorry, we pulled .5d shorty after release due to a database corruption issue.  It's root caused and should be fixed in next release, in meantime please revert to .5c.  To prevent this happening in the future we're planning to add something to back up old db.

**Comment by sonus9** [comment] 2016-03-20 23:46
Thanks!

**Comment by Gloorf** [comment] 2016-03-23 16:03
Fixed in 98dd1051.

**Closed by Gloorf** 2016-03-23 16:03 UTC
